### ISSUE TITLE
我有一個問題

### ISSUE THREAD

**Issue by roberthsu2003** [roberthsu2003/__11209python_school__#1]
### 下方為巢狀迴圈
- 問題1:執行有錯誤

> 有誰可以解決
```
#學生總分為300
#有些學生可以加分5%
#如果加分超過300,就以300分為準
import pyinputplus as pyip
scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
is_add = input("請問是否符合加分條件?(y,n)")
if is_add == "y":
    scores *= 1.05
    if scores > 300:
        scores = 300
print(f"學生總分是:{scores}")
```

1. 以下為[連結](http://www.google.com.tw)
<img width="661" alt="截圖 2023-09-20 上午8 56 38" src="https://github.com/roberthsu2003/__11209python_school__/assets/1614274/819e7353-bab7-4a44-be1c-d4bbe21868e0">

**Comment by roberthsu2003** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
>  1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

**Comment by maggiechian926** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
>  1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

老師好

**Comment by cute511131** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
> 1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

哈囉

**Comment by roberthsu2003** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
>  1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

**Comment by dspm0980711658** [comment]
..............................

**Comment by Rachelyah** [comment]
> > ### 下方為巢狀迴圈
> > 
> > * 問題1:執行有錯誤
> > 
> > > 有誰可以解決
> > 
> > 
> > ```
> > #學生總分為300
> > #有些學生可以加分5%
> > #如果加分超過300,就以300分為準
> > import pyinputplus as pyip
> > scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> > is_add = input("請問是否符合加分條件?(y,n)")
> > if is_add == "y":
> >     scores *= 1.05
> >     if scores > 300:
> >         scores = 300
> > print(f"學生總分是:{scores}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. 以下為[連結](http://www.google.com.tw)
> > 
> > <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

123

**Comment by dspm0980711658** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
> 1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

......

**Comment by miking8899** [comment]
> ### 下方為巢狀迴圈
> * 問題1:執行有錯誤
> 
> > 有誰可以解決
> 
> ```
> #學生總分為300
> #有些學生可以加分5%
> #如果加分超過300,就以300分為準
> import pyinputplus as pyip
> scores = pyip.inputInt(prompt="請輸入學生分數(最高分300分):",min=0,max=300)
> is_add = input("請問是否符合加分條件?(y,n)")
> if is_add == "y":
>     scores *= 1.05
>     if scores > 300:
>         scores = 300
> print(f"學生總分是:{scores}")
> ```
> 
> 1. 以下為[連結](http://www.google.com.tw)
> 
> <img alt="截圖 2023-09-20 上午8 56 38" width="661" src="https://user-images.githubusercontent.com/1614274/269128425-819e7353-bab7-4a44-be1c-d4bbe21868e0.png">

Ok,已處理,感恩

**Comment by roberthsu2003** [comment]
關閉範例
