### ISSUE TITLE
海報聯絡人

### ISSUE THREAD

**Issue by ruth8607253** [roberthsu2003/__11209python_school__#2]
有人知道海報聯絡人是什麼嗎？

**Comment by maggiechian926** [comment]
是這個嗎？
"海報聯絡人" 通常指的是與某個活動、宣傳或事件相關的海報上列出的聯絡人。這個聯絡人通常負責提供更多相關資訊、回答問題、處理報名或購票事務，或者提供有關該活動的一般支援。海報上的聯絡人可能包括姓名、電話號碼、電子郵件地址或其他方式，以便人們可以輕鬆地聯絡他們以獲取更多訊息或參加活動。

**Comment by roberthsu2003** [comment]
關閉說明
